export const hobbies = [
    'Đọc sách',
    'Chơi game',
    'Du lịch',
    'Âm nhạc',
    'Nhiếp ảnh',
    'Nấu ăn',
    'Leo núi',
    'Nhảy múa',
    'Bơi lội',
    'Viết',
    'Vẽ',
    'Sơn',
    'Chạy',
    'Đạp xe',
    'Yoga',
    'Câu cá',
    'Cắm trại',
    'Lướt sóng',
    'Trượt ván',
    'Trượt tuyết',
    'Trượt băng',
    'Bắn cung',
    'Thuyền buồm',
    'Leo núi đá',
    'Trồng cây',
    'Quan sát chim',
    'Thiền',
    'Đan len',
    'Crochet',
    'Thủ công gỗ',
    'Dự án DIY',
    'Gốm sứ',
    'Khâu chần',
    'Thư pháp',
    'Sổ tay',
    'Gấp giấy',
    'Sưu tầm tem',
    'Sưu tầm tiền',
    'Sưu tầm đồ cổ',
    'Xây dựng mô hình',
    'Giải đố',
    'Cờ vua',
    'Trò chơi bảng',
    'Trò chơi bài',
    'Mẹo ảo thuật',
    'Tung hứng',
    'Nhảy múa ballroom',
    'Zumba',
    'Võ thuật',
    'Đấm bốc',
    'Đấu kiếm',
    'Thể dục dụng cụ',
    'Cử tạ',
    'Pilates',
    'Lặn bình khí',
    'Lặn với ống thở',
    'Kayak',
    'Đi thuyền',
    'Đứng lên chèo',
    'Cưỡi ngựa',
    'Tennis',
    'Cầu lông',
    'Golf',
    'Bóng đá',
    'Bóng rổ',
    'Bóng chày',
    'Bóng bầu dục',
    'Trượt băng nghệ thuật',
    'Bóng bàn',
    'Bóng chuyền',
    'Rugby',
    'Săn bắn',
    'Bắn súng',
    'Airsoft',
    'Paintball',
    'Laser Tag',
    'Nướng bánh',
    'Trang trí bánh',
    'Nấu bia',
    'Nếm rượu',
    'Làm phô mai',
    'Làm rượu tại nhà',
    'Nếm thức ăn',
    'Viết blog',
    'Vlogging',
    'Podcasting',
    'Diễn xuất',
    'Hài kịch',
    'Ma thuật',
    'Kể chuyện',
    'Improv',
    'Thiết kế trang phục',
    'Nghệ thuật trang điểm',
    'Thiết kế thời trang',
    'Làm trang sức',
    'May',
    'Thêu',
    'Xăm',
    'Làm nước hoa',
    'Gấp giấy',
    'Chiêm tinh',
    'Ngắm sao',
    'Robotics',
    'In 3D'
];





